### ISSUE TITLE
Switch back to previous audio source after exiting big picture mode?

### ISSUE THREAD

**Issue by Suffice** [cinterre/BigPictureAudioSwitch#1]
This works great still even though it's 5 years old! 

Just ran into a few hiccups:

First, it doesn't start right away after installing it, so I had to go to the programs directory and launch it from there. 

Second, I don't believe it's set to run automatically from startup, so I had to add a shortcut to the Startup directory.

Third, it doesn't switch back to the previously set audio source after exiting big picture mode, I would really like to see this.

Appreciate your work!

**Comment by cinterre** [comment]
Thanks, yeah I still use it myself and forget it's even there honestly.
For the first two hiccups, I mostly just didn't want it to be invasive, so as you said you do have to make it startup automatically yourself if you want it.

For the third hiccup it is currently setup so that it should switch back to the one it was on previously. It works for me at least, so not sure why it didn't. I've had it get a little mixed up some times if the audio devices have changed while it's running (as in new devices are plugged in or removed), but it should work otherwise. I would maybe sure you have the device you want it to revert back to set as your windows default, then right click the tray icon and pick the audio source you want to switch to again. I've found that seems to reset things if I ever do have an issue.

Glad you like it otherwise!
